#!/bin/bash
. gettext.sh
export TEXTDOMAIN="hebernate"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
guitool="zenity"

if (runlevel | grep -q [06]) || (pidof '/sbin/shutdown' > /dev/null); then
    echo -e "Do not suspend/hibernate because system is shuting down"
    exit 0
fi

#testing_purposes(){
## TRANSLATORS: you should ignore entirely this message, its only for my tests purposes in the new eltrans :)
#echo -e "$( eval_gettext "This sentence is here only for TEST-9 purposes" )"
#}

check_for_errors(){
    for i in 1 2 3 4 5
    do
        lines="$( dmesg | tail -n 30 | grep -i error | grep -qi sector )"

        if [[ "$lines" -gt "3" ]] ; then
            $guitool --info --text="$( eval_gettext "Warning: Looks like you've got errors on your hard disk after suspend/hibernate. Please open a terminal and run the command 'dmesg' to view them in detail. If you find errors on your hard disk, you should shutdown your computer and stop using these features immediately. Not doing this could damage your data seriously." )"
        fi

        sleep 3
    done
}

case $1 in
    --suspend)
        #warning-messages-elive suspend
        #setvolume mute
        sync

        # if not failed, is because we DID suspension correctly
        if ! /usr/sbin/pm-suspend 2>/tmp/.hebernate-$USER 1>&2 ; then
            #setvolume unmute
            #$guitool --error --text="$( cat /tmp/.hebernate-$USER )"
            el_speak_text -f "this computer has not suspension features, going to reboot instead"
            sleep 8
            reboot
        fi


        # BACK from suspsension
        #sync

        #sleep 10
        #sync
        #setvolume unmute
        rm -f /tmp/.hebernate-$USER
        (
            soundfile="/usr/share/sounds/elive/system-restored.mp3"
            cat "$soundfile" >/dev/null &
            timeout 30 mpg123 -q "$soundfile" || true
            check_for_errors
        ) &
        exit
        ;;


    --hibernate|--hibernation|--hebernate)
        if ! swapon -s | grep -Ev "^Filename.*Type" | grep -q "/dev/" ; then
            el_speak_text -f "you don't have a swap partition enabled, to use hibernation you need one"
            sleep 8
            is_hebernate_failed=1
        fi

        if ! grep -qsE "LINUX_DEFAULT.*resume=" /etc/defaul/grub ; then
            el_speak_text -f "your bootloader needs to have the resume entry in order to use hibernation, we suggest to reinstall to theh last version of elive to make this working"
            sleep 14
            is_hebernate_failed=1
        fi

        if ((is_hebernate_failed)) ; then
            exit
        fi


        #setvolume mute
        sync

        if ! /usr/sbin/pm-hibernate 2>/tmp/.hebernate-$USER 1>&2 ; then
            #setvolume unmute
            #$guitool --error --text="$( cat /tmp/.hebernate-$USER )"
            el_speak_text -f "this computer has not hibernation features, going to reboot instead"
            sleep 8
            reboot
        fi


        #sleep 10
        #sync
        #setvolume unmute
        rm -f "/tmp/.hebernate-$USER"
        (
            soundfile="/usr/share/sounds/elive/system-restored.mp3"
            cat "$soundfile" >/dev/null &
            timeout 30 mpg123 -q "$soundfile" || true
            check_for_errors
        ) &
        ;;
    *)
        echo -e "\nElive Suspend/Hibernate tool\nUsage: $(basename $0) (--suspend|--hibernate)"
        exit
        ;;
esac
