#!/bin/bash
. gettext.sh
export TEXTDOMAIN="hebernate"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
guitool="zenity"

if (runlevel | grep -q [06]) || (pidof '/sbin/shutdown' > /dev/null); then
    echo -e "Do not suspend/hibernate because system is shuting down"
    exit 0
fi

#testing_purposes(){
## TRANSLATORS: you should ignore entirely this message, its only for my tests purposes in the new eltrans :)
#echo -e "$( eval_gettext "This sentence is here only for TEST-9 purposes" )"
#}

check_for_errors(){
    for i in 1 2 3 4 5
    do
        lines="$( dmesg | tail -n 30 | grep -i error | grep -qi sector )"

        if [[ "$lines" -gt "3" ]] ; then
            $guitool --info --text="$( eval_gettext "Warning: Looks like you have errors on your hard disk after suspend/hibernate. Please open a terminal and run the command 'dmesg' to view them in detail. If you find errors on your hard disk, you should shut down your computer and stop using these features immediately. Not doing may cause data loss." )"
        fi

        sleep 3
    done
}

case $1 in
    --suspend)
        #warning-messages-elive suspend
        #setvolume mute
        sync

        # you cannot suspend in live mode, no matter what
        if grep -q "boot=live" /proc/cmdline ; then
            el_speak_text -f "ignoring suspension in live mode, please install elive in your computer to use this feature"
            sleep 7
            #reboot
            exit
            #sleep 10 # do not talk after this
        fi

        # if not failed, is because we DID suspension correctly
        if ! /usr/sbin/pm-suspend 2>/tmp/.hebernate-$USER 1>&2 ; then
            #setvolume unmute
            #$guitool --error --text="$( cat /tmp/.hebernate-$USER )"
            sleep 1
            el_speak_text -f "this computer doesn't has suspension features, please use another option"
            sleep 11
            #reboot
            exit
        fi


        # BACK from suspsension
        #sync

        #sleep 10
        sleep 1
        #sync
        #setvolume unmute
        rm -f /tmp/.hebernate-$USER
        (
            soundfile="/usr/share/sounds/elive/system-restored.mp3"
            precache "$soundfile" 2>/dev/null
            timeout 30 mpg123 -q "$soundfile" || true
            check_for_errors
        ) &
        exit
        ;;


    --hibernate|--hibernation|--hebernate)

        # reboot if we are in live mode, no matter what, hibernation not works
        if grep -q "boot=live" /proc/cmdline ; then
            #el_speak_text -f "you cannot hibernate while you are in live mode"
            el_speak_text -f "ignoring suspension in live mode, please install elive in your computer to use this feature"

            sleep 9
            is_hebernate_failed=1
        fi

        if ! ((is_hebernate_failed)) ; then
            if ! swapon -s | grep -q "^/dev/" ; then
                el_speak_text -f "you don't have a swap partition enabled, to use hibernation you need one"
                sleep 7
                is_hebernate_failed=1
            fi
        fi

        if ! ((is_hebernate_failed)) ; then
            if ! grep -qsE "LINUX_DEFAULT.*resume=" /etc/default/grub ; then
                el_speak_text -f "we suggest to reinstall to the last version of elive, including a swap partition, to have hibernation working"
                sleep 12
                is_hebernate_failed=1
            fi
        fi


        #setvolume mute
        sync

        if ! /usr/sbin/pm-hibernate 2>/tmp/.hebernate-$USER 1>&2 ; then
            #setvolume unmute
            #$guitool --error --text="$( cat /tmp/.hebernate-$USER )"
            el_speak_text -f "sorry, this computer has not hibernation features available"
            sleep 9
            is_hebernate_failed=1
        fi


        # exit here
        if ((is_hebernate_failed)) ; then
            # reboot because e17 blocks if don't exit successfully
            #reboot
            exit
        fi


        #sleep 10
        sleep 1
        #sync
        #setvolume unmute
        rm -f "/tmp/.hebernate-$USER"
        (
            soundfile="/usr/share/sounds/elive/system-restored.mp3"
            precache "$soundfile" 2>/dev/null
            timeout 30 mpg123 -q "$soundfile" || true
            check_for_errors
        ) &
        ;;
    *)
        echo -e "\nElive Suspend/Hibernate tool\nUsage: $(basename $0) (--suspend|--hibernate)"
        exit
        ;;
esac
